name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository (Latest)
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
          check-latest: true
      - name: Run npm install
        run: npm install
      - name: Run tests
        run: npm run test
