name: Deploy Site to S3

on:
  # Maintain this as a manual step until we add automated tests
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          check-latest: true
        run: npm install
        run: npm run build
